# Create an Array


In [28]:
import numpy as np
arr_1D = np.array([1, 2, 3, 4, 5])
print("arr_1D: ", arr_1D)

arr_1D:  [1 2 3 4 5]


# 2D Array

In [3]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]]) 
print("arr_2D: ", arr_2D)


arr_2D:  [[1 2 3]
 [4 5 6]]


# 3D Array

In [30]:
arr_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("arr_3D: ", arr_3D)



arr_3D:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Special array 

In [6]:
zeros = np.zeros((3, 4))
ones = np.ones((2, 3)) 
full = np.full((2, 2), 7) 
identity = np.eye(3) 
range_arr = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)

print("Zeros:", zeros, "\nones", ones, "\nfull:", full, "\nidentity:", identity, "\nrange_arr:", range_arr, "\nlinspace:", linspace)


Zeros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
ones [[1. 1. 1.]
 [1. 1. 1.]] 
full: [[7 7]
 [7 7]] 
identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
range_arr: [0 2 4 6 8] 
linspace: [0.   0.25 0.5  0.75 1.  ]


# Array Shapes and Dimensions

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Shape:", arr.shape)                  
print("Dimensions:", arr.ndim)              
print("Size:", arr.size)                    
print("Data type:", arr.dtype)              
print("Item size:", arr.itemsize, "bytes")  


Shape: (4, 3)
Dimensions: 2
Size: 12
Data type: int32
Item size: 4 bytes


#  Indexing and Slicing

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Row 1:", arr[1])                    
print("Column 2:", arr[:, 2])              
print("First 2 rows:", arr[:2])            
print("Last 2 columns:", arr[:, -2:])      
print("Middle section:", arr[1:, 1:3])     


Row 1: [4 5 6]
Column 2: [ 3  6  9 12]
First 2 rows: [[1 2 3]
 [4 5 6]]
Last 2 columns: [[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
Middle section: [[ 5  6]
 [ 8  9]
 [11 12]]


# Broadcasting Rules

In [9]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result = arr_2d + arr_1d
print("result:", result)


result: [[11 22 33]
 [14 25 36]]


# Mathematical Operations

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Mean:", np.mean(arr))                    
print("Standard deviation:", np.std(arr))       
print("Min:", np.min(arr), "Max:", np.max(arr)) 
print("Product:", np.prod(arr))


Mean: 6.5
Standard deviation: 3.452052529534663
Min: 1 Max: 12
Product: 479001600


In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix multiplication:", np.dot(a, b))                 
print("Element-wise multiplication:", np.multiply(a, b))  
print("Determinant:", np.linalg.det(a))                  
print("Inverse:", np.linalg.inv(a))                       
print("Eigenvalues:", np.linalg.eigvals(a))               


Matrix multiplication: [[19 22]
 [43 50]]
Element-wise multiplication: [[ 5 12]
 [21 32]]
Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]


# Get unique value

In [12]:
arr = np.array([1,2,3,4,4,5])
unique_element = np.unique(arr) 
print("unique_element: ", unique_element )


unique_element:  [1 2 3 4 5]


# 	reshape(): Change the shape of an array without changing its data.

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)


# flatten(): Convert a multi-dimensional array into a 1D array.



In [14]:
arr2 = np.array([[1,2,3],[4,5,6]])
flat = arr2.flatten()
print("flat: ", flat)


flat:  [1 2 3 4 5 6]


# 	transpose(): Swap axes of an array.

In [15]:
arr3 = np.array([[1,2,3],[4,5,6]])
transposed = arr3.T
print("transposed: ", transposed )


transposed:  [[1 4]
 [2 5]
 [3 6]]


# 	1D. Concatenation:

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
conc = np.concatenate([a,b])
print("conc: ", conc)


conc:  [1 2 3 4 5 6]


# 2D. Concatenation

In [17]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

conc0 = np.concatenate([A,B], axis=0)  
conc1 = np.concatenate([A,B], axis=1)  
print("conc0 :",conc, "\nconc1",conc1)


conc0 : [1 2 3 4 5 6] 
conc1 [[1 2 5 6]
 [3 4 7 8]]


# 	vstack(): Converts 1D arrays into 2D rows automatically.

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
ans = np.vstack([a,b]) 
print("ans: ",ans)


ans:  [[1 2 3]
 [4 5 6]]


# 	hstack(): Convenient for combining feature columns.
## 1D Hstack

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
h = np.hstack([a,b]) 
print("h: ",h)


h:  [1 2 3 4 5 6]


#	2D.  Horizontal stack combining:

In [21]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
h2 = np.hstack([A,B])
print("h2: ",h2)


h2:  [[1 2 5 6]
 [3 4 7 8]]


In [24]:
import time, sys
size = 1000000
python_list = list(range(size))
numpy_array = np.arange(size)

start = time.time()
result_list = [x + 5 for x in python_list]
list_time = time.time()-start

start = time.time()
result_array = numpy_array + 5
numpy_time = time.time() - start
print(f"Addition: List: {list_time:.5f}s, NumPy: {numpy_time:.5f}s") 
print(f"NumPy is {list_time/numpy_time:.0f}x faster")


Addition: List: 0.06977s, NumPy: 0.00252s
NumPy is 28x faster


In [25]:
print(f"Python list memory: {sys.getsizeof(python_list)} bytes") 
print(f"NumPy array memory: {numpy_array.nbytes} bytes")         
print(f"NumPy uses {sys.getsizeof(python_list)/numpy_array.nbytes:.1f}x less memory") 


Python list memory: 8000056 bytes
NumPy array memory: 4000000 bytes
NumPy uses 2.0x less memory
