In [1]:
import torch
print(torch.__version__)


2.8.0+cpu


# Tensors Creation operation:

In [2]:
import torch
a = torch.tensor([1, 2, 3])
print("a: ",a)


a:  tensor([1, 2, 3])


In [3]:
b = torch.zeros(3, 3)
c = torch.ones(2, 2)
print("b: ", b, "\nc: ",c)


b:  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 
c:  tensor([[1., 1.],
        [1., 1.]])


In [4]:
d = torch.rand(2, 3)
print("d: ",d)


d:  tensor([[0.9786, 0.9241, 0.7763],
        [0.5064, 0.9386, 0.6819]])


In [5]:
import numpy as np
arr = np.array([4, 5, 6])
e = torch.from_numpy(arr)
print("e: ",e)


e:  tensor([4, 5, 6], dtype=torch.int32)


# Shape and Dimesnsion

In [6]:
scalar = torch.tensor(5)
print(scalar)
print("Shape:", scalar.shape)
print("Dimensions:", scalar.ndim)


tensor(5)
Shape: torch.Size([])
Dimensions: 0


# 1D Tensor

In [7]:
vector = torch.tensor([1, 2, 3, 4])
print(vector)
print("Shape:", vector.shape)
print("Dimensions:", vector.ndim)


tensor([1, 2, 3, 4])
Shape: torch.Size([4])
Dimensions: 1


# 2D Tensor

In [8]:
matrix = torch.rand(2, 3)
print(matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)


tensor([[0.1625, 0.3700, 0.6770],
        [0.0182, 0.5937, 0.3781]])
Shape: torch.Size([2, 3])
Dimensions: 2


# 3D Tensor

In [9]:
image = torch.rand(3, 224, 224)            # (Channels, Height, Width)
print("Shape:", image.shape)
print("Dimensions:", image.ndim)


Shape: torch.Size([3, 224, 224])
Dimensions: 3


# 4D tensor

In [10]:
batch_images = torch.rand(8, 3, 224, 224)  # (Batch, Channels, Height, Width)
print("Shape:", batch_images.shape)
print("Dimensions:", batch_images.ndim)


Shape: torch.Size([8, 3, 224, 224])
Dimensions: 4


# Data Type 

In [11]:
float32 = torch.tensor([1.0, 2.0], dtype=torch.float32)  
float16 = torch.tensor([1.0, 2.0], dtype=torch.float16)  
int64   = torch.tensor([1, 2], dtype=torch.long)         

print(float32, "| dtype:", float32.dtype)
print(float16, "| dtype:", float16.dtype)
print(int64,   "| dtype:", int64.dtype)


tensor([1., 2.]) | dtype: torch.float32
tensor([1., 2.], dtype=torch.float16) | dtype: torch.float16
tensor([1, 2]) | dtype: torch.int64


# Type Conversion

In [12]:
x = torch.tensor([1, 2, 3])
x_float  = x.float()    
x_double = x.double()   
x_half   = x.half()     

print(x, "| dtype:", x.dtype)
print(x_float, "| dtype:", x_float.dtype)
print(x_double, "| dtype:", x_double.dtype)
print(x_half, "| dtype:", x_half.dtype)


tensor([1, 2, 3]) | dtype: torch.int64
tensor([1., 2., 3.]) | dtype: torch.float32
tensor([1., 2., 3.], dtype=torch.float64) | dtype: torch.float64
tensor([1., 2., 3.], dtype=torch.float16) | dtype: torch.float16


# Memory Analysis

In [13]:
print("\nMemory Usage:")
print("Float32 size:", torch.tensor([1.0], dtype=torch.float32).element_size(), "bytes")
print("Float16 size:", torch.tensor([1.0], dtype=torch.float16).element_size(), "bytes")
print("Int64 size  :", torch.tensor([1], dtype=torch.int64).element_size(), "bytes")



Memory Usage:
Float32 size: 4 bytes
Float16 size: 2 bytes
Int64 size  : 8 bytes


# Device Selection

In [14]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Selected device:", device)


Selected device: cpu


In [15]:
x = torch.tensor([1.0, 2.0, 3.0])
print("\nOriginal tensor device:", x.device)

# Move tensor to selected device
x = x.to(device)
print("Tensor after .to(device):", x.device)

# Move back to CPU
x_cpu = x.cpu()
print("Tensor moved to CPU:", x_cpu.device)

# Move to GPU (only if available)
if torch.cuda.is_available():
    x_gpu = x_cpu.cuda()
    print("Tensor moved to GPU:", x_gpu.device)
else:
    print("CUDA not available, skipping GPU move")



Original tensor device: cpu
Tensor after .to(device): cpu
Tensor moved to CPU: cpu
CUDA not available, skipping GPU move


# Tensor to Numpy

In [16]:
import torch
import numpy as np

tensor = torch.tensor([[1, 2], [3, 4]])
numpy_array = tensor.numpy()

print("Tensor:", tensor)
print("NumPy array:", numpy_array)


Tensor: tensor([[1, 2],
        [3, 4]])
NumPy array: [[1 2]
 [3 4]]


# Numpy to Tensor

In [17]:
import numpy as np
import torch

numpy_array = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(numpy_array)

print("NumPy array:", numpy_array)
print("Tensor:", tensor)


NumPy array: [[1 2]
 [3 4]]
Tensor: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


# Automatic Differentiation 

In [18]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x + 1

y.backward()
print("Value of y:", y.item())
print("Gradient dy/dx:", x.grad)


Value of y: 11.0
Gradient dy/dx: tensor(7.)


# Linear Model

In [20]:
import torch.nn as nn
import torch
model = nn.Linear(1, 1)
x = torch.tensor([[2.0]])
y_true = torch.tensor([[8.0]])

# Forward pass
y_pred = model(x)

# Loss function
loss_fn = nn.MSELoss()
loss = loss_fn(y_pred, y_true)

# Backward pass
loss.backward()

# Print gradients
print("Gradient of weight:", model.weight.grad)
print("Gradient of bias:", model.bias.grad)


Gradient of weight: tensor([[-25.3137]])
Gradient of bias: tensor([-12.6568])


# Activation functions

In [21]:
import torch
import torch.nn as nn

x = torch.tensor([[-2.0, -1.0, 0.0, 1.0, 2.0]])
print("Input Tensor:")
print(x)

relu = nn.ReLU()
sigmoid = nn.Sigmoid()
tanh = nn.Tanh()
softmax = nn.Softmax(dim=1)

print("\nReLU Output:")
print(relu(x))

print("\nSigmoid Output:")
print(sigmoid(x))

print("\nTanh Output:")


Input Tensor:
tensor([[-2., -1.,  0.,  1.,  2.]])

ReLU Output:
tensor([[0., 0., 0., 1., 2.]])

Sigmoid Output:
tensor([[0.1192, 0.2689, 0.5000, 0.7311, 0.8808]])

Tanh Output:


# Loss Function

In [22]:
import torch
import torch.nn as nn

y_true = torch.tensor([3.0, 5.0])
y_pred = torch.tensor([2.5, 4.0], requires_grad=True)

loss_fn = nn.MSELoss()          # Define loss function
loss = loss_fn(y_pred, y_true)  # Compute loss
loss.backward()                  # Backward pass

print("True values:", y_true)
print("Predicted values:", y_pred)
print("Loss value:", loss.item())
print("Gradient w.r.t predictions:", y_pred.grad)


True values: tensor([3., 5.])
Predicted values: tensor([2.5000, 4.0000], requires_grad=True)
Loss value: 0.625
Gradient w.r.t predictions: tensor([-0.5000, -1.0000])
