# Device Selection

In [2]:
import tensorflow as tf

device = "/GPU:0" if tf.config.list_physical_devices('GPU') else "/CPU:0"
print("Selected device:", device)


Selected device: /CPU:0


# Device Management

In [3]:
device = "/GPU:0" if tf.config.list_physical_devices('GPU') else "/CPU:0"

# Create tensor
x = tf.constant([1.0, 2.0, 3.0])
print("Original tensor device:", x.device)

# Move tensor to selected device
with tf.device(device):
    x_device = tf.constant([1.0, 2.0, 3.0])
print("Tensor after device placement:", x_device.device)

# Move tensor to CPU
with tf.device("/CPU:0"):
    x_cpu = tf.constant([1.0, 2.0, 3.0])
print("Tensor moved to CPU:", x_cpu.device)

# Move tensor to GPU (only if available)
if tf.config.list_physical_devices('GPU'):
    with tf.device("/GPU:0"):
        x_gpu = tf.constant([1.0, 2.0, 3.0])
    print("Tensor moved to GPU:", x_gpu.device)

else:
    print("CUDA not available, skipping GPU move")


Original tensor device: /job:localhost/replica:0/task:0/device:CPU:0
Tensor after device placement: /job:localhost/replica:0/task:0/device:CPU:0
Tensor moved to CPU: /job:localhost/replica:0/task:0/device:CPU:0
CUDA not available, skipping GPU move


In [4]:
import tensorflow as tf
a = tf.constant([1.5, 2.5, 3.5], dtype=tf.float32)
print(a.dtype)  


<dtype: 'float32'>


In [5]:
a = tf.constant([1.5, 2.5, 3.5], dtype=tf.float32)
b = tf.cast(a, dtype=tf.float64)  

print(a.dtype)  
print(b.dtype)  


<dtype: 'float32'>
<dtype: 'float64'>


# Tensor Types

In [6]:
import tensorflow as tf
tensor_list = tf.constant([1, 2, 3, 4])
print("Tensor from list:")
print(tensor_list)


Tensor from list:
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [7]:
tensor_zeros = tf.zeros((2, 3))
print("\nZero Tensor:")
print(tensor_zeros)

tensor_ones = tf.ones((2, 3))
print("\nOne Tensor:")
print(tensor_ones)



Zero Tensor:
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

One Tensor:
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [8]:
tensor_random = tf.random.uniform((2, 2))
print("\nRandom Value Tensor:")
print(tensor_random)



Random Value Tensor:
tf.Tensor(
[[0.30324185 0.17965424]
 [0.29822695 0.34574485]], shape=(2, 2), dtype=float32)


In [10]:
import numpy as np
np_array = np.array([10, 20, 30])
tensor_numpy = tf.convert_to_tensor(np_array)
print("\nTensor from NumPy array:")
print(tensor_numpy)



Tensor from NumPy array:
tf.Tensor([10 20 30], shape=(3,), dtype=int64)


In [11]:
tensor_range = tf.range(1, 6)
print("\nRange Tensor:")
print(tensor_range)



Range Tensor:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [12]:
tensor_eye = tf.eye(3)
print("\nIdentity (Eye) Tensor:")
print(tensor_eye)



Identity (Eye) Tensor:
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


# Tensor creation and check shape and dimension

In [13]:
scalar = tf.constant(5)
print(scalar)
print("Shape:", scalar.shape)
print("Dimensions:", scalar.ndim)


tf.Tensor(5, shape=(), dtype=int32)
Shape: ()
Dimensions: 0


In [14]:
vector = tf.constant([1, 2, 3, 4])
print(vector)
print("Shape:", vector.shape)
print("Dimensions:", vector.ndim)


tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Shape: (4,)
Dimensions: 1


In [15]:
matrix = tf.random.uniform((2, 3))
print(matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)


tf.Tensor(
[[0.19205022 0.30808938 0.31714237]
 [0.8569219  0.69450426 0.18057418]], shape=(2, 3), dtype=float32)
Shape: (2, 3)
Dimensions: 2


In [16]:
tensor_3d = tf.random.uniform((2, 3, 4))
print(tensor_3d)
print("Shape:", tensor_3d.shape)
print("Dimensions:", tensor_3d.ndim)


tf.Tensor(
[[[0.16942406 0.35473585 0.04855597 0.3007058 ]
  [0.9150151  0.03034723 0.84796786 0.5813154 ]
  [0.86364865 0.75975657 0.16438961 0.9229069 ]]

 [[0.44973397 0.5606756  0.45931983 0.03190482]
  [0.07884681 0.9461187  0.12225211 0.607887  ]
  [0.40346503 0.76417136 0.42393386 0.81894624]]], shape=(2, 3, 4), dtype=float32)
Shape: (2, 3, 4)
Dimensions: 3


# Tesnor shape manipulation

In [17]:
tensor = tf.constant([1, 2, 3, 4, 5, 6])
reshaped = tf.reshape(tensor, (2, 3))
print(reshaped)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


# Broadcasting in tensorflow

In [18]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
b = tf.constant([1, 2, 3])

print(a + b)


tf.Tensor(
[[2 4 6]
 [5 7 9]], shape=(2, 3), dtype=int32)


# Mathematical operations

In [19]:
tensor = tf.constant([1, 2, 3, 4])

print(tf.reduce_sum(tensor))
print(tf.reduce_mean(tensor))
print(tf.reduce_max(tensor))


tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


# tensor Rank

In [20]:
scalar = tf.constant(5)
print("Scalar Rank:", scalar.ndim)

vector = tf.constant([1, 2, 3])
print("Vector Rank:", vector.ndim)

matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix Rank:", matrix.ndim)

tensor_3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("3D Tensor Rank:", tensor_3d.ndim)


Scalar Rank: 0
Vector Rank: 1
Matrix Rank: 2
3D Tensor Rank: 3


# Tensorflow Session

In [21]:
tf.compat.v1.disable_eager_execution()

# Define constants
a = tf.constant(10)
b = tf.constant(20)

# Operation
c = a + b

# Create a session
with tf.compat.v1.Session() as sess:
    result = sess.run(c)
    print("Result:", result)



Result: 30


In [25]:
!pip install tensorflow-estimator



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Activation Function

In [3]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
x = tf.constant([[-2.0, -1.0, 0.0, 1.0, 2.0]])

# Activation functions
relu = tf.keras.activations.relu(x)
sigmoid = tf.keras.activations.sigmoid(x)
tanh = tf.keras.activations.tanh(x)
softmax = tf.keras.activations.softmax(x)

# Execute graph
with tf.compat.v1.Session() as sess:
    print("Input Tensor:")
    print(sess.run(x))

    print("\nReLU Output:")
    print(sess.run(relu))

    print("\nSigmoid Output:")
    print(sess.run(sigmoid))

    print("\nTanh Output:")
    print(sess.run(tanh))

    print("\nSoftmax Output:")
    print(sess.run(softmax))


Input Tensor:
[[-2. -1.  0.  1.  2.]]

ReLU Output:
[[0. 0. 0. 1. 2.]]

Sigmoid Output:
[[0.11920294 0.2689414  0.5        0.73105854 0.8807971 ]]

Tanh Output:
[[-0.9640276 -0.7615942  0.         0.7615942  0.9640276]]

Softmax Output:
[[0.01165623 0.03168492 0.08612854 0.23412165 0.6364086 ]]


# Loss Function

In [4]:
tf.compat.v1.disable_eager_execution()
y_true = tf.constant([1, 0, 1, 1], dtype=tf.float32)
y_pred = tf.constant([0.9, 0.2, 0.7, 0.4], dtype=tf.float32)

mse = tf.keras.losses.MeanSquaredError()(y_true, y_pred)
mae = tf.keras.losses.MeanAbsoluteError()(y_true, y_pred)
bce = tf.keras.losses.BinaryCrossentropy()(y_true, y_pred)

with tf.compat.v1.Session() as sess:
    print("Mean Squared Error:", sess.run(mse))
    print("Mean Absolute Error:", sess.run(mae))
    print("Binary Cross-Entropy:", sess.run(bce))


Mean Squared Error: 0.125
Mean Absolute Error: 0.3
Binary Cross-Entropy: 0.40036747
